<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>expresso</groupId>
    <artifactId>expresso</artifactId>
    <version>1.0-Mediano</version>
    <packaging>jar</packaging>
    <name>expresso</name>
    
    <properties>
        <maven.compiler.release>23</maven.compiler.release>
        <antlr4.plugin.version>4.13.1</antlr4.plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    
    <dependencies>
        <!-- Runtime de ANTLR para usar los parsers generados -->
        <dependency>
            <groupId>org.antlr</groupId>
            <artifactId>antlr4-runtime</artifactId>
            <version>${antlr4.plugin.version}</version>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
            <!-- Plugin para generar parser/lexer desde .g4 -->
            <plugin>
                <groupId>org.antlr</groupId>
                <artifactId>antlr4-maven-plugin</artifactId>
                <version>${antlr4.plugin.version}</version>
                <executions>
                    <execution>
                        <id>antlr</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>antlr4</goal>
                        </goals>
                        <configuration>
                            <visitor>true</visitor>
                            <listener>true</listener>
                            <packageName>expresso</packageName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            
            <!-- Plugin para compilación -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>

            
            <!-- Exec plugin para correr el REPL -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <mainClass>expresso.cli.Repl</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>